[package]
name = "iota-mam"
version = "0.1.0"
authors = ["Vlad Semenov <vlad.semenov@iota.org>"]
edition = "2018"
license = "MIT"
readme = "README.md"
keywords = ["iota", "mam"]
description = "A rust implementation of the IOTA MAM"

[lib]
name = "iota_mam"

[workspace]
members = [
    "iota-mam-core",
    "iota-mam-protobuf3",
    "iota-mam-app",
]

[dependencies]
iota-mam-core = { version = "0.1.0", path = "iota-mam-core" }
iota-mam-protobuf3 = { version = "0.1.0", path = "iota-mam-protobuf3" }
iota-mam-app = { version = "0.1.0", path = "iota-mam-app" }

#[dev-dependencies]
#iota-client = "0.3.0"
#iota-model = "0.3.0"

[patch.crates-io]
iota-client = { path = "../iota-lib-rs/iota-client" }
