[package]
name = "iota-mam"
version = "0.1.0"
authors = ["Vlad Semenov <semenov.vlad.by@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "iota_mam"
path = "lib.rs"

#TODO: make `iota-mam` a member of `bee` workspace?
#TODO: add `mam-apps` crate?

#[dependencies]
#troika-rust = "0.1.1"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "bench"
harness = false

[profile.dev]
opt-level = 3
#debug = false

[profile.release]
opt-level = 3
