[package]
name = "iota-mam"
version = "0.1.0"
authors = ["Vlad Semenov <vlad.semenov@iota.org>"]
edition = "2018"
license = "Apache-2.0/MIT"
readme = "README.md"
keywords = ["iota", "mam"]
description = "A rust implementation of the IOTA MAM"

[lib]
name = "iota_mam"

[workspace]
members = [
    "iota-mam-core",
    "iota-mam-protobuf3",
    "iota-mam-app",
    "iota-mam-app-channel",
]

[dependencies]
iota-mam-core = { version = "0.1.0", path = "iota-mam-core" }
iota-mam-protobuf3 = { version = "0.1.0", path = "iota-mam-protobuf3" }
iota-mam-app = { version = "0.1.0", path = "iota-mam-app" }
iota-mam-app-channel = { version = "0.1.0", path = "iota-mam-app-channel" }

[patch.crates-io]
# iota-lib-rs "0.4.0" has an issue with "Content-Type"
iota-lib-rs = { path = '../iota-lib-rs' }
